# Generated by Django 4.2.11 on 2024-06-19 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255, null=True)),
                ('redirect', models.CharField(max_length=255, null=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('component', models.CharField(max_length=255, null=True)),
                ('layout', models.CharField(blank=True, max_length=50, null=True)),
                ('keep_alive', models.IntegerField(null=True)),
                ('method', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('show', models.BooleanField()),
                ('enable', models.BooleanField()),
                ('order', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admin_backend.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRolesRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_backend.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField(null=True)),
                ('nick_name', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermissionsPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_backend.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_backend.role')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
