# Generated by Django 3.2.3 on 2024-04-25 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazProduct',
            fields=[
                ('asin', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('model', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('upc', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cpu_brand', models.CharField(default='Intel', max_length=50)),
                ('cpu_model', models.CharField(default='', max_length=50)),
                ('cpu_serial', models.CharField(default='i7', max_length=50)),
                ('disk_slot_type', models.CharField(default='', max_length=50)),
                ('disk_total_size', models.CharField(default='512', max_length=50)),
                ('mem_size_by_slot', models.CharField(default='8-8', max_length=50)),
                ('mem_slot_type', models.CharField(default='2-0', max_length=50)),
                ('mem_total_size', models.CharField(default='16', max_length=50)),
                ('mem_type', models.CharField(default='DDR4', max_length=50)),
                ('os', models.CharField(default='Windows', max_length=50)),
                ('os_generation', models.CharField(default='11', max_length=50)),
                ('os_version', models.CharField(default='Home', max_length=50)),
                ('screen', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=256)),
                ('product', models.CharField(max_length=1024)),
                ('qty', models.IntegerField()),
                ('supplier', models.CharField(max_length=256)),
                ('upc', models.CharField(max_length=256)),
                ('upc_full', models.CharField(default='', max_length=256)),
                ('wh_id', models.CharField(max_length=256)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryExtra',
            fields=[
                ('upc', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('purchase_po', models.CharField(default='', max_length=50)),
                ('purchase_link', models.CharField(default='', max_length=50)),
                ('purchase_price', models.CharField(default='', max_length=50)),
                ('product_type', models.CharField(default='laptop', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255, null=True)),
                ('redirect', models.CharField(max_length=255, null=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('component', models.CharField(max_length=255, null=True)),
                ('layout', models.CharField(blank=True, max_length=50, null=True)),
                ('keep_alive', models.IntegerField(null=True)),
                ('method', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('show', models.BooleanField()),
                ('enable', models.BooleanField()),
                ('order', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='amaz_products.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRolesRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amaz_products.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StandardProductAsin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=100)),
                ('operatingSystem', models.CharField(default='home', max_length=50)),
                ('memory', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('asin', models.CharField(default='', max_length=50)),
                ('comment', models.CharField(default='', max_length=500)),
            ],
            options={
                'unique_together': {('upc', 'operatingSystem', 'memory', 'disk', 'asin')},
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_rank_reference', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('rank', models.BigIntegerField()),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amaz_products.amazproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField(null=True)),
                ('nick_name', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amaz_products.amazproduct')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermissionsPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amaz_products.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amaz_products.role')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
